# --- DO NOT CHANGE THIS ---------------
config-version: 2
# --------------------------------------
uuid: ''
name: ''
kills: 0.0
death_by_player: 0.0
death_by_nonplayer: 0.0
coordinates:
  overworld: [ ]
  nether: [ ]
  the_end: [ ]
