name: SD_SMP
version: 2.0
author: Sir Daniel III
main: com.sirdanieliii.SD_SMP.SD_SMP
api-version: 1.16
commands:
  coords:
    description: Saves coords so you won't get lost
    usage: /coords <action> <arguments>
  death:
    description: Statistics about your deaths and murders :D
    usage: /death <stat>
  ivan:
    description: <OP Required> Spawns an Ivan (Donkey or Dog)
    usage: /ivan <type>
  wand:
    description: <OP Required> Spawns a weapon of the Gods
    usage: /wand
  SMP:
    description: Displays every SD_SMP command
    usage: /SMP
permissions:
  sd_smp.god.wand:
    description: Lets you use the wand
    default: op
  sd_smp.ivan.*:
    description: Gives access to all Ivan commands
    children:
      sd_smp.ivan.dog: true
      sd_smp.ivan.donkey: true
  sd_smp.ivan.dog:
    description: Spawns a dog named Ivan
    default: op
  sd_smp.ivan.donkey:
    description: Spawns a donkey named Ivan
    default: op
  sd_smp.coords.*:
    description: Gives access to most Coords commands
    children:
      sd_smp.coords.clear: true
      sd_smp.coords.list: true
      sd_smp.coords.send: true
      sd_smp.coords.set: true
  sd_smp.coords.clear:
    description: Clears a saved coordinate
    default: true
  sd_smp.coords.list:
    description: Lists a saved coordinate
    default: true
  sd_smp.coords.send:
    description: Sends a saved coordinate
    default: true
  sd_smp.coords.set:
    description: Sets a saved coordinate
    default: true
  sd_smp.coords.teleport:
    description: Allows you to teleport to a saved coordinate
    default: false
  sd_smp.death.*:
    description: Gives access to all Death commands
    children:
      sd_smp.death.kdr: true
      sd_smp.death.murders: true
      sd_smp.death.nonplayer: true
      sd_smp.death.player: true
      sd_smp.death.total: true
  sd_smp.death.kdr:
    description: Returns KDR value
    default: true
  sd_smp.death.murders:
    description: Returns murder count
    default: true
  sd_smp.death.nonplayer:
    description: Returns death count (No PVP)
    default: true
  sd_smp.death.player:
    description: Returns death count (Only PVP)
    default: true
  sd_smp.death.total:
    description: Returns lifetime death count
    default: true