name: SD_SMP
version: 1.0
author: Sir Daniel III
main: com.sirdanieliii.SD_SMP.SD_SMP
api-version: 1.16
commands:
  coords:
    description: Saves coords so you won't get lost
    usage: /coords <action> <arguments>
  death:
    description: Statistics about your deaths and murders :D
    usage: /death <stat>
  ivan:
    description: <OP Required> Spawns an Ivan (Donkey or Dog)
    usage: /ivan <type>
  wand:
    description: <OP Required> Spawns a weapon of the Gods
    usage: /wand
  SMP:
    description: Displays every SD_SMP command
    usage: /SMP
